{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"provenance":[],"authorship_tag":"ABX9TyMiIpxUqivIBDDvTvuHJMe8"},"kernelspec":{"name":"python3","display_name":"Python 3"},"language_info":{"name":"python"}},"cells":[{"cell_type":"code","execution_count":null,"metadata":{"id":"R_JWdOMYCNUu"},"outputs":[],"source":["# Para crear/definir/implementar nuestra propia excepcion debemos considerar la clase Exception\n","# Esta clase Exception, como en otras vistas, va a ser la clase padre de nuestra propia excepcion\n","\n","# Definir una subclase : MiExcepcionPersonalizada\n","# Clase padre : Exception\n","\n","class MiExcepcionPersonalizada(Exception):\n","    pass"]},{"cell_type":"code","source":["# Lancemos/ejecutemos/instanciemos mi subclase personalziada\n","raise MiExcepcionPersonalizada()"],"metadata":{"colab":{"base_uri":"https://localhost:8080/","height":158},"id":"Ik6gh_E9ELhy","executionInfo":{"status":"error","timestamp":1724363448534,"user_tz":300,"elapsed":318,"user":{"displayName":"Rodrigo Jara Espinoza","userId":"06062723213486373109"}},"outputId":"1aad1d37-740b-4716-ab73-ed0b95fb854d"},"execution_count":null,"outputs":[{"output_type":"error","ename":"MiExcepcionPersonalizada","evalue":"","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mMiExcepcionPersonalizada\u001b[0m                  Traceback (most recent call last)","\u001b[0;32m<ipython-input-2-024e2f20dc65>\u001b[0m in \u001b[0;36m<cell line: 2>\u001b[0;34m()\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[0;31m# Lancemos/ejecutemos/instanciemos mi subclase personalziada\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 2\u001b[0;31m \u001b[0;32mraise\u001b[0m \u001b[0mMiExcepcionPersonalizada\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m","\u001b[0;31mMiExcepcionPersonalizada\u001b[0m: "]}]},{"cell_type":"code","source":["# Documentacion MiExcepcionPersonalizada\n","help(MiExcepcionPersonalizada)"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"collapsed":true,"id":"8t976wnMEy_a","executionInfo":{"status":"ok","timestamp":1724363540486,"user_tz":300,"elapsed":336,"user":{"displayName":"Rodrigo Jara Espinoza","userId":"06062723213486373109"}},"outputId":"64ed3cc0-33c5-4c33-9a71-dd71880f4c92"},"execution_count":null,"outputs":[{"output_type":"stream","name":"stdout","text":["Help on class MiExcepcionPersonalizada in module __main__:\n","\n","class MiExcepcionPersonalizada(builtins.Exception)\n"," |  Method resolution order:\n"," |      MiExcepcionPersonalizada\n"," |      builtins.Exception\n"," |      builtins.BaseException\n"," |      builtins.object\n"," |  \n"," |  Data descriptors defined here:\n"," |  \n"," |  __weakref__\n"," |      list of weak references to the object (if defined)\n"," |  \n"," |  ----------------------------------------------------------------------\n"," |  Methods inherited from builtins.Exception:\n"," |  \n"," |  __init__(self, /, *args, **kwargs)\n"," |      Initialize self.  See help(type(self)) for accurate signature.\n"," |  \n"," |  ----------------------------------------------------------------------\n"," |  Static methods inherited from builtins.Exception:\n"," |  \n"," |  __new__(*args, **kwargs) from builtins.type\n"," |      Create and return a new object.  See help(type) for accurate signature.\n"," |  \n"," |  ----------------------------------------------------------------------\n"," |  Methods inherited from builtins.BaseException:\n"," |  \n"," |  __delattr__(self, name, /)\n"," |      Implement delattr(self, name).\n"," |  \n"," |  __getattribute__(self, name, /)\n"," |      Return getattr(self, name).\n"," |  \n"," |  __reduce__(...)\n"," |      Helper for pickle.\n"," |  \n"," |  __repr__(self, /)\n"," |      Return repr(self).\n"," |  \n"," |  __setattr__(self, name, value, /)\n"," |      Implement setattr(self, name, value).\n"," |  \n"," |  __setstate__(...)\n"," |  \n"," |  __str__(self, /)\n"," |      Return str(self).\n"," |  \n"," |  with_traceback(...)\n"," |      Exception.with_traceback(tb) --\n"," |      set self.__traceback__ to tb and return self.\n"," |  \n"," |  ----------------------------------------------------------------------\n"," |  Data descriptors inherited from builtins.BaseException:\n"," |  \n"," |  __cause__\n"," |      exception cause\n"," |  \n"," |  __context__\n"," |      exception context\n"," |  \n"," |  __dict__\n"," |  \n"," |  __suppress_context__\n"," |  \n"," |  __traceback__\n"," |  \n"," |  args\n","\n"]}]},{"cell_type":"code","source":["# Lista de metodos que se puede aplicar a un objeto que es instancia de la clase MiExcepcionPersonalizada\n","x1 = MiExcepcionPersonalizada()\n","dir(x1)"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"M8Id14xoF-JC","executionInfo":{"status":"ok","timestamp":1724363906535,"user_tz":300,"elapsed":366,"user":{"displayName":"Rodrigo Jara Espinoza","userId":"06062723213486373109"}},"outputId":"ed754b74-9f65-4f59-94fa-18ae84a992e5"},"execution_count":null,"outputs":[{"output_type":"execute_result","data":{"text/plain":["['__cause__',\n"," '__class__',\n"," '__context__',\n"," '__delattr__',\n"," '__dict__',\n"," '__dir__',\n"," '__doc__',\n"," '__eq__',\n"," '__format__',\n"," '__ge__',\n"," '__getattribute__',\n"," '__gt__',\n"," '__hash__',\n"," '__init__',\n"," '__init_subclass__',\n"," '__le__',\n"," '__lt__',\n"," '__module__',\n"," '__ne__',\n"," '__new__',\n"," '__reduce__',\n"," '__reduce_ex__',\n"," '__repr__',\n"," '__setattr__',\n"," '__setstate__',\n"," '__sizeof__',\n"," '__str__',\n"," '__subclasshook__',\n"," '__suppress_context__',\n"," '__traceback__',\n"," '__weakref__',\n"," 'args',\n"," 'with_traceback']"]},"metadata":{},"execution_count":4}]},{"cell_type":"code","source":["# Tambien podemos pasar argumentos de entrada al lanzar nuestra subclase\n","# Ejemplo : Pasemos dos argumentos al lanzar nuestra excepcion. Para ello necesitamos\n","# modificar la funcion __init__() de la siguiente manera\n","\n","# Modifiquemos el metodo __init()__ de nuestra excepcion personalizada\n","class MiExcepcionPersonalizada(Exception):\n","  def __init__(self, parametro1, parametro2):\n","    self.parametro1 = parametro1\n","    self.parametro2 = parametro2"],"metadata":{"id":"4z6fs6fVFKfR"},"execution_count":null,"outputs":[]},{"cell_type":"code","source":["# __init()__ se ejecuta cuando instancio un objeto de esa clase\n","# siempre el primer argumento es \"self\""],"metadata":{"id":"_B1iIHtwG0IJ"},"execution_count":null,"outputs":[]},{"cell_type":"code","source":["#\n","x2 = MiExcepcionPersonalizada(\"Python\", \"Intermedio\")"],"metadata":{"id":"OX35gACFHg4I"},"execution_count":null,"outputs":[]}]}